# Generated by Django 5.1.2 on 2024-12-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_details',
            field=models.CharField(max_length=500),
        ),
    ]
