# Generated by Django 5.1.2 on 2024-12-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='service_level',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('driver', 'driver')], max_length=255),
        ),
    ]
