# Generated by Django 5.1.2 on 2024-12-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_remove_shipment_service_level_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'driver'), ('admin', 'admin'), ('user', 'user')], max_length=255),
        ),
    ]
